#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
#        - App\Entity\Album:
#        - App\Entity\Image:
#            form:
#                fields:
#                    { property: 'imageFile', type: 'file' }
#            list:
#                fields:
#                    - { property: 'image_name', template: 'vich_uploader_image.html.twig', type: 'image', base_path: '/images/uploads' }
#            show:
#                fields:
#                    - { property: 'image', type: 'image', base_path: '/images/uploads' }
#        - App\Entity\Comment:
#        - App\Entity\UserData:
